version: "3.9"

services:
  chemical-interactions:
    image: public.ecr.aws/h7r1e4h2/chemical-interactions:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
  chemical-preview:
    image: public.ecr.aws/h7r1e4h2/chemical-preview:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  chemical-properties:
    image: public.ecr.aws/h7r1e4h2/chemical-properties:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  coordinate-align:
    image: public.ecr.aws/h7r1e4h2/coordinate-align:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
  docking-autodock4:
    image: public.ecr.aws/h7r1e4h2/docking-autodock4:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py --algorithm=autodock4 -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  docking-smina:
    image: public.ecr.aws/h7r1e4h2/docking-smina:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  esp:
    image: public.ecr.aws/h7r1e4h2/esp:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  hydrogens:
    image: public.ecr.aws/h7r1e4h2/hydrogens:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  minimization:
    image: public.ecr.aws/h7r1e4h2/minimization:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  realtime-scoring:
    image: public.ecr.aws/h7r1e4h2/realtime-scoring:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  rmsd:
    image: public.ecr.aws/h7r1e4h2/rmsd:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  structure-prep:
    image: public.ecr.aws/h7r1e4h2/structure-prep:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
    command: python run.py -a ${NTS_HOST} -p ${NTS_PORT} -k ${NTS_KEY}
  vault:
    image: public.ecr.aws/h7r1e4h2/vault:latest
    ports:
      - "${NTS_PORT-8888}"
    env_file:
      - .env
      - .env.vault
    networks:
      - vault-network
  vault-server:
    image: public.ecr.aws/h7r1e4h2/vault-server:latest
    networks:
      - vault-network
    ports:
      - 8000:8000
      - 443:443
    volumes:
     - vault-volume:/root
    env_file:
      - .env
volumes:
  vault-volume:
networks:
  vault-network:
    driver: bridge

    
