#!/bin/bash

# Use this script to prepare a server to deploy when changes pushed

ENV_FILE="/home/ec2-user/.env"
TARGET="/home/ec2-user/nanome-starter-stack"
GIT_DIR="/home/ec2-user/nanome-starter-stack.git"
BRANCH="deploy-test"

if [ -f $ENV_FILE ]
then
  echo "LOADING .env file"
  export $(cat $ENV_FILE | sed 's/#.*//g' | xargs)
fi

echo NTS_HOST=$NTS_HOST
echo NTS_PORT=$NTS_PORT

while read oldrev newrev ref
do
        # only checking out the master (or whatever branch you would like to deploy)
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
                $TARGET/deploy.sh -a $NTS_HOST -p $NTS_PORT
        else
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done